#!/usr/bin/env bash
# save the current /etc/hosts file to /etc/hosts.backup
cp /etc/hosts /etc/hosts.backup
# rm entries for localhost of /etc/hosts
sed -i '/localhost/d' /etc/hosts
# rm entries for facebook of /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts
# add new entrie localhost resolving to 127.0.0.1
echo "127.0.0.1 localhost" >> /etc/hosts
