#!/usr/bin/env bash
# save the current /etc/hosts file to /etc/hosts.backup
cp /etc/hosts /etc/hosts.backup
# rm entries for localhost of /etc/hosts
echo -n > /etc/hosts
# add new entrie localhost resolving to 127.0.0.1
echo "127.0.0.2 localhost" >> /etc/hosts
# add new entrie facebook resolving to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
